apiVersion: v1
kind: ConfigMap
metadata:
  namespace: wazuh
  name: config
data:
  config: |
    address-pools:
    - name: wazuh-ip-space
      protocol: layer2
      addresses:
  #Set local addresses for external IP 
      - 192.168.30.172-192.168.30.173